[build]
  command = "cd client && GOOS=js GOARCH=wasm go build -o app.wasm ."
  publish = "client"

[build.environment]
  GO_VERSION = "1.20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200